[package]
name = "mun_codegen"
version = "0.2.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"
description = "LLVM IR code generation for Mun"
documentation = "https://docs.mun-lang.org/v0.2"
readme = "README.md"
homepage = "https://mun-lang.org"
repository = "https://github.com/mun-lang/mun"
license = "MIT OR Apache-2.0"
keywords = ["game", "hot-reloading", "language", "mun", "scripting"]
categories = ["Game development", "Mun"]

[dependencies]
abi = { version = "=0.2.0", path = "../mun_abi", package = "mun_abi" }
hir = { version = "=0.2.0", path = "../mun_hir", package = "mun_hir" }
itertools = "0.9.0"
mun_codegen_macros = { path = "../mun_codegen_macros", package = "mun_codegen_macros" }
mun_target = { version = "=0.2.0", path = "../mun_target" }
mun_lld = { version = "=80.0.0", path = "../mun_lld" }
anyhow = "1.0.31"
thiserror = "1.0.19"
salsa = "0.15.0"
md5="0.6.1"
array-init="0.1.0"
tempfile = "3"
paste = "0.1.6"
parking_lot = "0.10"
inkwell = { version = "=0.1.0-llvm8sample", features = ["llvm8-0"]}
by_address = "1.0.4"

[dev-dependencies]
abi = { path = "../mun_abi", package = "mun_abi" }
insta = "0.16"
libloader = { path = "../mun_libloader", package = "mun_libloader" }
mun_test = { path = "../mun_test" }
runtime = { path = "../mun_runtime", package = "mun_runtime" }

[build-dependencies]
semver = "0.9.0"
regex = "1.3.1"
